modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="spiders"
version="${version}"
displayName="Spiders"
authors="Horrormods"
description='''A mod that adds spiders to Minecraft.'''

[[dependencies.spiders]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.spiders]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.spiders]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.40,)"
ordering="AFTER"
side="BOTH"